const friendshipQuotes = [
  { text: "Friendship is born at that moment when one person says to another, ‘What! You too? I thought I was the only one.’", author: "C.S. Lewis" },
  { text: "A real friend is one who walks in when the rest of the world walks out.", author: "Walter Winchell" },
  { text: "True friendship comes when the silence between two people is comfortable.", author: "David Tyson" },
  { text: "Friendship is the only cement that will ever hold the world together.", author: "Woodrow Wilson" },
  { text: "Friends are the siblings God never gave us.", author: "Mencius" },
  { text: "A friend is someone who gives you total freedom to be yourself.", author: "Jim Morrison" },
  { text: "My best friend is the one who brings out the best in me.", author: "Henry Ford" },
  { text: "Friendship is always a sweet responsibility, never an opportunity.", author: "Kahlil Gibran" },
  { text: "A true friend never gets in your way unless you happen to be going down.", author: "Arnold H. Glasow" },
  { text: "The most beautiful discovery true friends make is that they can grow separately without growing apart.", author: "Elisabeth Foley" },
  { text: "There is nothing on this earth more to be prized than true friendship.", author: "Thomas Aquinas" },
  { text: "Friends are those rare people who ask how we are and then wait to hear the answer.", author: "Ed Cunningham" },
  { text: "A friend is what the heart needs all the time.", author: "Henry Van Dyke" },
  { text: "In the cookie of life, friends are the chocolate chips.", author: "Salman Rushdie" },
  { text: "Friendship improves happiness and abates misery, by the doubling of our joy and the dividing of our grief.", author: "Marcus Tullius Cicero" },
  { text: "A single rose can be my garden… a single friend, my world.", author: "Leo Buscaglia" },
  { text: "A friend is one who overlooks your broken fence and admires the flowers in your garden.", author: "Unknown" },
  { text: "Friends are the family you choose.", author: "Jess C. Scott" },
  { text: "True friends are like diamonds — bright, beautiful, valuable, and always in style.", author: "Nicole Richie" },
  { text: "There are no strangers here; only friends you haven’t yet met.", author: "William Butler Yeats" },
  { text: "Friendship is the golden thread that ties the heart of all the world.", author: "John Evelyn" },
  { text: "A good friend knows all your stories. A best friend helped you write them.", author: "Unknown" },
  { text: "Friendship isn’t about whom you have known the longest… it’s about who came and never left your side.", author: "Yolanda Hadid" },
  { text: "The language of friendship is not words but meanings.", author: "Henry David Thoreau" },
  { text: "Friendship multiplies the good of life and divides the evil.", author: "Baltasar Gracian" },
  { text: "The only way to have a friend is to be one.", author: "Ralph Waldo Emerson" },
  { text: "Life is partly what we make it, and partly what it is made by the friends we choose.", author: "Tennessee Williams" },
  { text: "A loyal friend laughs at your jokes when they’re not so good, and sympathizes with your problems when they’re not so bad.", author: "Arnold H. Glasow" },
  { text: "Friends show their love in times of trouble, not in happiness.", author: "Euripides" },
  { text: "A true friend is the greatest of all blessings.", author: "Francois de La Rochefoucauld" }
];

export default friendshipQuotes;
