const loveQuotes = [
  { text: "Love is composed of a single soul inhabiting two bodies.", author: "Aristotle" },
  { text: "Being deeply loved by someone gives you strength, while loving someone deeply gives you courage.", author: "Lao Tzu" },
  { text: "Where there is love there is life.", author: "Mahatma Gandhi" },
  { text: "To love and be loved is to feel the sun from both sides.", author: "David Viscott" },
  { text: "Love is not about how many days, months, or years you have been together. It’s about how much you love each other every single day.", author: "Unknown" },
  { text: "The best thing to hold onto in life is each other.", author: "Audrey Hepburn" },
  { text: "You know you're in love when you can't fall asleep because reality is finally better than your dreams.", author: "Dr. Seuss" },
  { text: "Love recognizes no barriers. It jumps hurdles, leaps fences, penetrates walls to arrive at its destination full of hope.", author: "Maya Angelou" },
  { text: "Love is that condition in which the happiness of another person is essential to your own.", author: "Robert A. Heinlein" },
  { text: "The greatest thing you'll ever learn is just to love and be loved in return.", author: "Eden Ahbez" },
  { text: "I have decided to stick with love. Hate is too great a burden to bear.", author: "Martin Luther King Jr." },
  { text: "You don't love someone because they're perfect, you love them in spite of the fact that they're not.", author: "Jodi Picoult" },
  { text: "To love is nothing. To be loved is something. But to love and be loved, that’s everything.", author: "T. Tolis" },
  { text: "Love doesn’t make the world go round. Love is what makes the ride worthwhile.", author: "Franklin P. Jones" },
  { text: "Love is when the other person's happiness is more important than your own.", author: "H. Jackson Brown Jr." },
  { text: "The best and most beautiful things in this world cannot be seen or even heard, but must be felt with the heart.", author: "Helen Keller" },
  { text: "Love is a friendship set to music.", author: "Joseph Campbell" },
  { text: "We are shaped and fashioned by those we love.", author: "Goethe" },
  { text: "There is no remedy for love but to love more.", author: "Henry David Thoreau" },
  { text: "Love is not only something you feel, it is something you do.", author: "David Wilkerson" },
  { text: "I swear I couldn’t love you more than I do right now, and yet I know I will tomorrow.", author: "Leo Christopher" },
  { text: "In all the world, there is no heart for me like yours.", author: "Maya Angelou" },
  { text: "To love is to burn, to be on fire.", author: "Jane Austen" },
  { text: "I would rather spend one lifetime with you, than face all the ages of this world alone.", author: "J.R.R. Tolkien" },
  { text: "If I know what love is, it is because of you.", author: "Hermann Hesse" },
  { text: "You are my today and all of my tomorrows.", author: "Leo Christopher" },
  { text: "Every love story is beautiful, but ours is my favorite.", author: "Unknown" },
  { text: "Love is the flower you've got to let grow.", author: "John Lennon" },
  { text: "Love cures people—both the ones who give it and the ones who receive it.", author: "Karl Menninger" },
  { text: "You call it madness, but I call it love.", author: "Don Byas" }
];

export default loveQuotes;
